# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: 
          name: Running Jest tests
          command: yarn test

      - run: 
          name: Deploying test results to codecov.io
          command: bash <(curl -s https://codecov.io/bash)

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc

      # - run:
      #     name: Publish package
      #     command: npm publish

      - run:
          name: Add GitHub Pages remote
          command: git remote add storybook git@github.com:infinitecsolutions/infinitecsolutions.github.io.git

      - run:
          name: Deploy story-book
          command: yarn deploy-storybook --ci
        


